### ISSUE TITLE
How to use this library with gradle

### ISSUE THREAD

**Issue by stiwari99** [jwgmeligmeyling/hibernate-types-querydsl-apt#28]
I tried to use this with gradle but not working.

I also tried copying your code directly into my project but that seems not to be registering extensions. Could you help with it

**Comment by stiwari99** [comment]
I was able to use it with gradle, see https://stackoverflow.com/questions/75625807/service-loader-not-cant-find-providers-when-using-gradle-but-works-with-maven

Repo https://github.com/bigbang4u2/query-dsl-hibernate-types is working with gradle

**Comment by jwgmeligmeyling** [comment]
Thanks for sharing!
